"""
A list of effects
"""
from ed_engineer_shopping_list_builder.printable_enum import PrintableEnum


# pylint: disable=too-few-public-methods
class ExperimentalEffect(PrintableEnum):
    """
    Component experimental effects
    """

    ANGLED_PLATING = "Angled Plating"
    AUTO_LOADER = "Auto Loader"
    BLAST_BLOCK = "Blast Block"
    BOSS_CELLS = "Boss Cells"
    CLUSTER_CAPACITOR = "Cluster Capacitor"
    CONCORDANT_SEQUENCE = "Concordant Sequence"
    CORROSIVE_SHELL = "Corrosive Shell"
    DAZZLE_SHELL = "Dazzle Shell"
    DEEP_CHARGE = "Deep Charge"
    DEEP_PLATING = "Deep Plating"
    DISPERSAL_FIELD = "Dispersal Field"
    DOUBLE_BRACED = "Double Braced"
    DRAG_DRIVES = "Drag Drives"
    DRAG_MUNITION = "Drag Munition"
    DRIVE_DISTRIBUTORS = "Drive Distributors"
    EMISSIVE_MUNITIONS = "Emissive Munitions"
    FAST_CHARGE = "Fast Charge"
    FEEDBACK_CASCADE = "Feedback Cascade"
    FLOW_CONTROL = "Flow Control"
    FORCE_BLOCK = "Force Block"
    FORCE_SHELL = "Force Shell"
    FSD_INTERRUPT = "FSD_Interrupt (Dumbfire only)"
    HIGH_YIELD_SHELL = "High Yield Shell"
    HI_CAP = "Hi-cap"
    INCENDIARY_ROUNDS = "Incendiary Rounds"
    INERTIAL_IMPACT = "Inertial Impact"
    ION_DISRUPTOR = "Ion Disruptor"
    LAYERED_PLATING = "Layered Plating"
    LO_DRAW = "Lo-draw"
    MASS_LOCK_MUNITION = "Mass Lock Munition"
    MASS_MANAGER = "Mass Manager"
    MONSTERED = "Monstered"
    MULTI_SERVOS = "Multi-Servos"
    MULTI_WEAVE = "Multi-weave"
    OVERLOAD_MUNITIONS = "Overload Munitions"
    OVERSIZED = "Oversized"
    PENETRATOR_MUNITIONS = "Penetrator Munitions (Dumbfire only)"
    PENETRATOR_PAYLOAD = "Penetrator Payload"
    PHASING_SEQUENCE = "Phasing Sequence"
    PLASMA_SLUG = "Plasma Slug"
    RADIANT_CANISTER = "Radiant Canister"
    RECYCLING_CELLS = "Recycling Cells"
    REFLECTIVE_PLATING = "Reflective Plating"
    REGENERATION_SEQUENCE = "Regeneration Sequence"
    REVERBERATING_CASCADE = "Reverberating Cascade"
    SCRAMBLE_SPECTRUM = "Scramble Spectrum"
    SCREENING_SHELL = "Screening Shell"
    SHIFT_LOCK_CANISTER = "Shift-Lock Canister"
    SMART_ROUNDS = "Smart Rounds"
    STRIPPED_DOWN = "Stripped Down"
    SUPER_CAPACITOR = "Super Capacitor"
    SUPER_CONDUITS = "Super Conduits"
    SUPER_PENETRATOR = "Super Penetrator"
    TARGET_LOCK_BREAKER = "Target Lock Breaker"
    THERMAL_CASCADE = "Thermal Cascade"
    THERMAL_CONDUIT = "Thermal Conduit"
    THERMAL_SHOCK = "Thermal Shock"
    THERMAL_SPREAD = "Thermal Spread"
    THERMAL_VENT = "Thermal Vent"
    THERMO_BLOCK = "Thermo Block"
