"""
A list of modifications
"""
from ed_engineer_shopping_list_builder.printable_enum import PrintableEnum


# pylint: disable=too-few-public-methods
class Modification(PrintableEnum):
    """
    Component modifications
    """

    AMMO_CAPACITY = "Ammo Capacity"
    ARMOURED = "Armoured"
    BLAST_RESISTANT = "Blast Resistant"
    BLAST_RESISTANT_HULL_REINFORCEMENT = "Blast Resistant Hull Reinforcement"
    CHARGE_ENHANCED = "Charge Enhanced"
    CLEAN_DRIVE_TUNING = "Clean Drive Tuning"
    DIRTY_DRIVE_TUNING = "Dirty Drive Tuning"
    DOUBLE_SHOT = "Double Shot"
    DRIVE_STRENGTHENING = "Drive Strengthening"
    EFFICIENT_WEAPON = "Efficient Weapon"
    ENGINE_FOCUSED = "Engine Focused"
    EXPANDED_FSD_INTERDICTOR_CAPTURE_ARC = "Expanded FSD Interdictor Capture Arc"
    ENHANCED_LOW_POWER_SHIELDS = "Enhanced, Enhanced, Low Power Shields"
    EXPANDED_PROBE_SCANNING_RADIUS = "Expanded Probe Scanning Radius"
    FAST_SCANNER = "Fast Scanner"
    FASTER_FSD_BOOT_SEQUENCE = "Faster FSD Boot Sequence"
    FOCUSED_WEAPON = "Focused Weapon"
    HEAVY_DUTY = "Heavy Duty"
    HEAVY_DUTY_HULL_REINFORCEMENT = "Heavy Duty Hull Reinforcement"
    HIGH_CAPACITY_MAGAZINE = "High Capacity Magazine"
    HIGH_CHARGE_CAPACITY = "High Charge Capacity"
    INCREASED_FSD_RANGE = "Increased FSD Range"
    KINETIC_RESISTANT = "Kinetic Resistant"
    KINETIC_RESISTANT_HULL_REINFORCEMENT = "Kinetic Resistant Hull Reinforcement"
    KINETIC_RESISTANT_SHIELDS = "Kinetic Resistant Shields"
    LIGHT_WEIGHT_SCANNER = "Light Weight Scanner"
    LIGHTWEIGHT = "Lightweight"
    LIGHTWEIGHT_HULL_REINFORCEMENT = "Lightweight Hull Reinforcement"
    LIGHTWEIGHT_MOUNT = "Lightweight Mount"
    LONG_RANGE_FSD_INTERDICTOR = "Long Range FSD Interdictor"
    LONG_RANGE_SCANNER = "Long Range Scanner"
    LONG_RANGE_WEAPON = "Long Range Weapon"
    LOW_EMISSIONS = "Low Emissions"
    OVERCHARGED = "Overcharged"
    OVERCHARGED_WEAPON = "Overcharged Weapon"
    RAPID_CHARGE = "Rapid Charge"
    RAPID_FIRE_MODIFICATION = "Rapid Fire Modification"
    REINFORCED = "Reinforced"
    REINFORCED_SHIELDS = "Reinforced Shields"
    RESISTANCE_AUGMENTED = "Resistance Augmented"
    SHIELDED = "Shielded"
    SHIELDED_FSD = "Shielded FSD"
    SHORT_RANGE_BLASTER = "Short Range Blaster"
    SPECIALISED = "Specialised"
    STURDY_MOUNT = "Sturdy Mount"
    SYSTEM_FOCUSED = "System Focused"
    THERMAL_RESISTANT = "Thermal Resistant"
    THERMAL_RESISTANT_HULL_REINFORCEMENT = "Thermal Resistant Hull Reinforcement"
    THERMAL_RESISTANT_SHIELDS = "Thermal Resistant Shields"
    WEAPON_FOCUSED = "Weapon Focused"
    WIDE_ANGLE_SCANNER = "Wide Angle Scanner"
